### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by tomashjorth** [Atvaark/BinderTool#2]
d:\binder>BinderTool.exe D:\A\Data5.bdt D:\Extract

Unhandled Exception: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at BinderTool.Core.Bhf4.Bhf4Entry.Read(Stream inputStream) in c:\Users\Tim\Documents\GitHub\BinderTool\BinderTool.Core\Bhf4\Bhf4Entry.cs:line 27
   at BinderTool.Core.Bhf4.Bhf4File.Read(Stream inputStream) in c:\Users\Tim\Documents\GitHub\BinderTool\BinderTool.Core\Bhf4\Bhf4File.cs:line 78
   at BinderTool.Program.UnpackBdf4File(Options options)
   at BinderTool.Program.Main(String[] args)

**Comment by Atvaark** [comment]
Which version are you using?

**Comment by tomashjorth** [comment]
Binder Tool 0.3
Dark Souls 3 v1.3 (steam)
Sorry for not being more specific.

**Comment by Atvaark** [comment]
Yeah, if you want to unpack DSIII files you have to use master / v0.4. I haven't uploaded a release yet because there are still some issues with file decryption and the dictionary.

**Comment by tomashjorth** [comment]
I see, sorry for the annoyance.
