### ISSUE TITLE
Can't extract .tpf.dcx

### ISSUE THREAD

**Issue by noxifoxi** [Atvaark/BinderTool#39]
I'm trying to extract texture files from that mod: https://www.nexusmods.com/darksoulsremastered/mods/145

The .ccm.dcx-files extract just fine, but I have no use for them and the .tpf.dcx stop with this error:
```ps1
> .\BinderTool.exe ..\font\english\DSFont24.tpf.dcx

Unhandled Exception: ICSharpCode.SharpZipLib.SharpZipBaseException: Unexpected EOF
   at ICSharpCode.SharpZipLib.Zip.Compression.Streams.InflaterInputBuffer.Fill()
   at ICSharpCode.SharpZipLib.Zip.Compression.Streams.InflaterInputStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at BinderTool.Core.Dcx.DeflateCompression.DecompressData(Byte[] compressedData, Int32 uncompressedSize)
   at BinderTool.Core.Dcx.DcxFile.Decompress()
   at BinderTool.Program.UnpackDcxFile(Options options)
   at BinderTool.Program.Main(String[] args)
```

**Comment by Atvaark** [comment]
Dark Souls was never supported, but I was able to fix the issue with the files of that mod.
The library used to decompress the archive couldn't read these files for some reason.

[v0.6.0-pre4](https://github.com/Atvaark/BinderTool/releases/tag/v0.6.0-pre4)
