### ISSUE TITLE
Unpacking error

### ISSUE THREAD

**Issue by Solaer1** [Atvaark/BinderTool#42]
When i try to unpack any file i either get an unsupported file error or on EndOfIOStreamException.
It still creates the folders but they just dont contain anything

**Comment by HunterAP23** [comment]
What version of the app are you using?
And what game are you trying to unpack with it?

**Comment by Solaer1** [comment]
Im using the latest release and trying to unpack ds3 files also latest version
error log:
 at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at BinderTool.Core.Bhf4.Bhf4Entry.Read(Stream inputStream)
   at BinderTool.Core.Bhf4.Bhf4File.Read(Stream inputStream)
   at BinderTool.Program.UnpackBdf4File(Options options)
   at BinderTool.Program.Main(String[] args)

**Comment by Solaer1** [comment]
I figurred it out, i assumed there only was one release since i didn't any other. Using the version meant for ds3 fixed the problem sorry for the annoyance
