### ISSUE TITLE
Dark souls 3 0.3.1 unhandled exception.

### ISSUE THREAD

**Issue by Soukmancer** [Atvaark/BinderTool#50]
Hi, I am trying to extract comfort mod to merge it with a loose mod but I am getting

Unhandled Exception: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at BinderTool.Core.Bhf4.Bhf4Entry.Read(Stream inputStream)
   at BinderTool.Core.Bhf4.Bhf4File.Read(Stream inputStream)
   at BinderTool.Program.UnpackBdf4File(Options options)
   at BinderTool.Program.Main(String[] args)

**Comment by Atvaark** [comment]
0.3.1 is too old for DS III. Could you try some of the newer versions such as
[v0.7.0-pre4 (Elden Ring)](https://github.com/Atvaark/BinderTool/releases/tag/v0.7.0-pre4)[](https://github.com/Atvaark/BinderTool/releases/latest),  [v0.7.0-pre2](https://github.com/Atvaark/BinderTool/releases/tag/v0.7.0-pre2) or [v0.5.2 (DSII, DSII SotFS, DSIII & Bloodborne)](https://github.com/Atvaark/BinderTool/releases/tag/v0.5.2)?
